# Generated by Django 4.1.4 on 2022-12-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('text', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts_list',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=40, unique=True)),
                ('post', models.ManyToManyField(blank=True, related_name='tags', to='post.post')),
            ],
            options={
                'db_table': 'tags_list',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.tag'),
        ),
    ]
